name: Build ZMK Firmware

"on":
  push:
  workflow_dispatch: 

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: togkey_zmk_source/zmk-config-togkeypad5/build.yaml
      config_path: togkey_zmk_source/zmk-config-togkeypad5/config
